/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:390f18f7-5099-4d74-9d53-587d6cece4c6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sWdPtk76E",
    "aws_user_pools_web_client_id": "18cebldgf0mvnrjhk6vckidc8e",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "BIRTHDATE",
        "EMAIL",
        "FAMILY_NAME",
        "GENDER",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "renewedmood-bucket180517-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
